name: log_plus
description: "Small, feature-rich logging package for Dart and Flutter. Written in pure Dart, with no dependencies."
version: 0.0.3
homepage: https://github.com/dev-kasibhatla/logs
repository: https://github.com/dev-kasibhatla/logs
issue_tracker: https://github.com/dev-kasibhatla/logs/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  test: ^1.15.3